namespace: cert-manager
issuer:
  name: letsencrypt-issuer
acme:
  solvers:
    api_token_secret:
      name: cloudflare-api-token-secrets
      key: api-token
    dns_zones:
      - datahub.asarad.org
      - api.datahub.asarad.org
      - my.datahub.asarad.org
      - im.datahub.asarad.org
